### ISSUE TITLE
#1314

### ISSUE THREAD

**Issue by egratt** [OneGiv/Support#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Terminal version

3.1.2

### Describe the bug

terminal 287 order 1314 does not have any transactions listed on portal but on machine a list of only today not yeserday 

and totals are all zero

### Expected Behavior

Bring the total and list all transactions

### Steps To Reproduce

grg

### Anything else?

gr

**Comment by aryehsilver** [comment]
@egratt this was found to be a bug and has been resolved. Closing as resolved.
