### ISSUE TITLE
make github private

### ISSUE THREAD

**Issue by Yoeli-Og** [OneGiv/Support#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

have some privacy

### Describe the solution you'd like

make github a private workspace/repository

**Comment by MrYossu** [comment]
This needs some discussion, as if we aren't using the repo for general support, we don't need it at all. If we are, then we need to make it private, but find a neat way of allowing new users to access it.

Closing for now, will discuss with AY.
