### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by egratt** [OneGiv/Support#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Portal type

Distributor

### Describe the bug

![image](https://user-images.githubusercontent.com/131248153/235359746-21efa279-140e-48fd-8630-edc443b10a8d.png)

**Comment by MrYossu** [comment]
I think we have fixed this. Please keep an eye on it and let me know if you get any more issues.

Thanks and kol tuv
Avrohom Yisroel
